version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules  # Prevent node_modules from being overwritten
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/jokedb
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: npm start

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jokedb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d  # Mount folder with the SQL initialization script
    ports:
      - "5432:5432"

volumes:
  pgdata:
